services:
   # ====================
  # MinIO (S3 Compatible)
  # ====================
  minio:
    image: minio/minio:latest
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio123
    command: server /data --console-address ":9001"
    ports:
      - "9000:9000"   # API S3
      - "9001:9001"   # Console UI
    volumes:
      - minio-data:/data
    restart: always
    networks:
      - data
    
  

  # ====================
  # Elasticsearch
  # ====================
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.11.1
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false   # Désactiver sécurité pour dev
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
    ports:
      - "9200:9200"
    volumes:
      - es-data:/usr/share/elasticsearch/data
    restart: always
    networks:
      - data
  
volumes:
  minio-data:
  es-data:
  
networks:
  data:
    driver: bridge
      