services:


  scheduler:
    volumes:
      - ./data:/usr/local/airflow/data
    networks:
      - data  
   # ====================
  # MinIO (S3 Compatible)
  # ====================
  minio:
    image: minio/minio:latest
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio123
    command: server /data --console-address ":9001"
    ports:
      - "9000:9000"   # API S3
      - "9001:9001"   # Console UI
    volumes:
      - minio-data:/data
    restart: always
    networks:
      - data
    
  



volumes:
  minio-data:
  data-volume:
    driver: local
  

  
  
networks:
  data:
    driver: bridge
      